### ISSUE TITLE
M1 mac build instructions

### ISSUE THREAD

**Issue by ickam** [goldendict/goldendict#1340]
Hi,
I'd like to build a native version of Goldendict for the m1 mac. I am hovewer struggling to get the right version of qt that would contain all the necessary extensions. 
Can you provide build instructions for m1 (arm64) mac, please?

**Comment by jiehaopenpen** [comment]
Same here!

**Comment by quantissimo** [comment]
I'm also interested in a build for m1 (arm64) mac

**Comment by 7468696e6b** [comment]
any updates?

**Comment by jeromecarney** [comment]
I spent a frustrating day trying to build GoldenDict for my new MacBook, without success. For now I'm resorting to other dictionary apps — Alpus is the closest match I've found to GoldenDict's robust feature set, although its interface is cumbersome.

It's been nearly a year since this topic was opened, and with the strong adoption rate of Apple Silicon, especially with the MacBook refresh, I hope GoldenDict will catch up soon.

**Comment by itkind** [comment]
Hi, I am in the same boat here. I wrote couple developers on Fiverr where you can pay people for a small task. Let's see who can build it and how much it will cost.

**Comment by vedgy** [comment]
GoldenDict has no regular contributors that use macOS. Apparently #1419 is the only recent Mac-specific contribution in years.

**Comment by nonwill** [comment]
It is a hardware-specific issue on Qt. Using Qt5 with M1 adapted and then compiling QtWebKit through the source code, there would be no problem at all. But things don't seem to be looking too good right now:
>https://www.qt.io/blog/qt-on-apple-silicon

**Comment by itkind** [comment]
I found some developer and payed him 60€ to compile GD for Mac on Qt 5.15. I should have it by Tuesday.

**Comment by jeromecarney** [comment]
@itkind : thanks for sharing — I really look forward to hearing how the custom build turns out.

**Comment by itkind** [comment]
@jeromecarney  
It seems that QT5.15 doen't work well with GD. Take a look: https://drive.google.com/file/d/1C11DJO8Y95Kb_GqUOKCEIzhB1QYlbzbA/view?usp=sharing

Issues: 
Font size is not saved
Some dictionaries are not indexing 
Some images are not loading 
Can't disable dictionaries by dragging them into the disable window.

**Comment by vedgy** [comment]
@itkind, sorry I have no access to or interest in macOS. The issues should be logged individually. Cross-platform issues have a chance to be fixed by GoldenDict developers. Platform-specific issues would probably require fixes contributed by macOS users.

**Comment by nonwill** [comment]
@itkind : I think you are fooled by scammers because Qt-5.15.2 doesn't support M1 mac yet.
[Fraudsters from some forums have been very active lately here](https://github.com/goldendict/goldendict/issues/1427#issuecomment-988881526). Submitting an issue as requested by the developer is the best option if you found a bug.

**Comment by nonwill** [comment]
@itkind : I think you were fooled by scammers because Qt-5.15.2 doesn't support M1 mac yet.
[Fraudsters from some forums have been very active lately here](https://github.com/goldendict/goldendict/issues/1427#issuecomment-988881526). Submitting an issue as requested by the developer is the best option if you found a bug.

**Comment by vedgy** [comment]
Windows build simplification and automation is discussed in #1428. Here are two more ideas to improve the situation of GoldenDict for macOS:
1. Conan is a multi-platform package manager, so it can be used to build GoldenDict's dependencies for macOS too.
2. If continuous integration for macOS is implemented, macOS users will enjoy fresh builds of each GoldenDict commit, just as GNU/Linux AppImage users do: https://github.com/goldendict/goldendict/wiki/Early-Access-Builds-for-Linux-Portable.

**Comment by itkind** [comment]
> I think you were fooled by scammers because Qt-5.15.2 doesn't support M1 mac yet.

I wasn't fooled because it was clear to me that it will be intel based. 


> [Fraudsters from some forums have been very active lately here](https://github.com/goldendict/goldendict/issues/1427#issuecomment-988881526).

I don't want to go into your personal discussion with other people but I want to make one thing clear, I like your GD port and I will use it. Thank you for doing it. 



> 2\. If continuous integration for macOS is implemented, macOS users will enjoy fresh builds of each GoldenDict commit

I can't contribute to this with my knowledge because I have none but I can contribute with money. I wish that someone would organize a crowdfunding and hire people who can improve the situation of GD. n

**Comment by vedgy** [comment]
Nothing prevents you from organizing a crowdfunding and hire someone to improve GoldenDict's usability on macOS. Hiring a developer to implement the CI would be more efficient than hiring each time you want a fresh GoldenDict build.

**Comment by itkind** [comment]
> Nothing prevents you from organizing a crowdfunding and hire someone to improve GoldenDict's usability on macOS. 

This is not completely true. I don't have the technical knowledge not the knowledge all required terms to communicate with developers and with the GD community. For example you speak about the implementation of the CI and I think 🤷🏽‍♀️

**Comment by vedgy** [comment]
If you don't feel up to the task, hopefully other GoldenDict macOS users are more technically knowledgeable.

If making his/her first GoldenDict build was relatively easy to the developer you had hired, implementing the CI should be straightforward too (possibly to another, more build-automation-experienced developer). It should be just a script that downloads and/or builds GoldenDict's dependencies, builds and packages GoldenDict itself. [This short script](https://github.com/goldendict/goldendict/blob/master/.travis.yml) implements the AppImage CI.

**Comment by ickam** [comment]
> macOS

I would just like to point out that the version of the app you provided @itkind still shows up as Intel version
<img width="1227" alt="Screenshot 2021-12-08 at 13 26 03" src="https://user-images.githubusercontent.com/29608654/145379916-8d258c2b-ca0c-4dff-9baf-e7a2b7db28d8.png">
So either you didn't let them know that you wanted an m1 (arm64) build or they just did what they wanted, 
Having said that, from little use since yesterday, it seems to work a bit better than what's available on homebrew.

**Comment by nonwill** [comment]
> > I think you were fooled by scammers because Qt-5.15.2 doesn't support M1 mac yet.
> 
> I wasn't fooled because it was clear to me that it will be intel based.

He had already stated that the intel based build is just right one he wanted.  

There is no open source version of Qt adapted to M1(arm64)  mac until now, except for the latest commercial version of Qt5 and Qt6. So what you can do is just waiting...

**Comment by vedgy** [comment]
> There is no open source version of Qt adapted to M1(arm64) mac until now, except for the latest commercial version of Qt5 and Qt6. So what you can do is just waiting...

The latest version of Qt 6 is free software. The necessary changes can be examined and ported over to the free version of Qt 5: https://community.kde.org/Qt5PatchCollection. [This post](https://www.mobileread.com/forums/showthread.php?p=4177264) seems to suggest this has been done already.

**Comment by nonwill** [comment]
> The necessary changes can be examined and ported over to the free version of Qt 5: https://community.kde.org/Qt5PatchCollection. [This post](https://www.mobileread.com/forums/showthread.php?p=4177264) seems to suggest this has been done already.

It may also need to be tested rigorously on macOS. 
Just to use the latest openssl and avoid memory leaks of Qt-5.12 and Qt-5.15, I have ported QNetWork and some main features from Qt-5.15 back to Qt-5.9.9 and did all tests on Windows only, it was a pain work that I can say...

**Comment by itkind** [comment]
@ickam I want to point out that he mac version of GD of Qt5.15 which I shared, is not perfect. The specialist had to pull back because of private reasons, means that he didn't revise the bugs but he also didn't want to be paid because of his unfinished work. After 3 or 4 months he will look again at it. The whole work took him just an hour.
I personally like the version of @nonwill more, because it is stable and fast.

**Comment by itkind** [comment]
@nonwill you need to give people more instructions how to use your version properly. 
First there is a bug in the macOS which blocks all copy to clipboard actions. The solution is to turn the accessibility access GD off and on again. 
The second thing is the cmd+c+c action which not only opens the popup window but the main GD window. The solution is to set a hotkey for the option called "Use the following hotkey to show or hide the main window". If the main window is hidden the popup window works great.  
Looking forward to see more of your great work!

**Comment by nonwill** [comment]
@itkind 
Sorry for that issues on Mac and Linux have got less attention in time. We are working on rewriting all the implementations. Due to lack of dedicated time and most users of GD++ are running Windows, currently full testing has been done for Windows only.
These issues should be better addressed in a future release which may be not that timely.

**Comment by vedgy** [comment]
@itkind, please take your discussion of illegal proprietary GoldenDict fork elsewhere please. This is an official issue tracker.

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict/releases/tag/pre-20220212-feature%2Fmac-action-5a2b58a

can someone kindly check this mac release build .
I have no macos to verify the release.

**Comment by 7468696e6b** [comment]
> https://github.com/xiaoyifang/goldendict/releases/tag/pre-20220212-feature%2Fmac-action-5a2b58a
> 
> can someone kindly check this mac release build . I have no macos to verify the release.

it works well
although it's still not M1 optimized (it's an intel build)

**Comment by xiaoyifang** [comment]
I have tried to build a arm64 support version which turns out to be too difficult.

Qt has not offered a arm64 m1 version which means one has to build from qt source to provide arm64 support.
and all the gd's dependencies such as ffmpeg libao etc.

or it will throw out an exception like 
> ld: symbol(s) not found for architecture arm64

**Comment by ngn999** [comment]
I build an apple silicon version here:

https://github.com/xiaoyifang/goldendict/issues/24#issuecomment-1078674954

I tested it on my Macbook pro M1, need more test.

**Comment by ngn999** [comment]
An universal version is [here](https://github.com/xiaoyifang/goldendict/releases/tag/v22.4.19-alpha.220422.e3766751).

**Comment by nonwill** [comment]
Here's [GoldenDict++OCR-macOS-12.13.1_universal based on Qt-5.15.3](https://github.com/nonwill/GoldenDict-OCR/releases/tag/test).

Notes: ffmpeg audio player is x86_64 build only, the fmod one is an universal build.

**Comment by nonwill** [comment]
Here's [GoldenDict++OCR-macOS-12.13.1_universal based on Qt-5.15.3](https://github.com/nonwill/GoldenDict-OCR/releases/tag/test).

Notes: _ffmpeg_ audio player is x86_64 build only, the [**_fmod_**](https://fmod.com/) one is an universal build.

**Comment by nonwill** [comment]
![z3e7n-o80q7](https://user-images.githubusercontent.com/46510529/166870046-b6004fb9-8991-436e-a8a7-c9014e3b58cd.gif)

**Comment by nonwill** [comment]
Add new [OCR plugin using Apple's Vision framework](https://www.autoptr.top/gdocr/GoldenDict-OCR-Language-Settings/)
![](https://www.autoptr.top/media/goldendict/macos_vision_ocr.png)

**Comment by liuyonghao156** [comment]
> Here's [GoldenDict++OCR-macOS-12.3.1_universal based on Qt-5.15.3](https://github.com/nonwill/GoldenDict-OCR/releases/tag/test).
> 
> Notes: _ffmpeg_ audio player is x86_64 build only, the [**_fmod_**](https://fmod.com/) one is an universal build. ![](https://user-images.githubusercontent.com/46510529/166870046-b6004fb9-8991-436e-a8a7-c9014e3b58cd.gif)

Please note that this version is non-free; use with your own discretion.

**Comment by nonwill** [comment]
@liuyonghao156 @ngn999
> Please note that this version is non-free; use with your own discretion.

You're getting antsy, aren't you? You can't get it right, can you, on both [free](https://www.autoptr.top/gdocr/GoldenDict-OCR-Deployment/) and unfree? 
And it's not that you are not technically proficient, but that not aiming at the right target and  not using your energy in the right way. 
Hahahahahaha, you'd be better to show off here than to go back to ploughing？Let's laugh out loud together, hahaha.

**Comment by nonwill** [comment]
@liuyonghao156 @ngn999 @xiaoyifang
> Please note that this version is non-free; use with your own discretion.

You techies are getting [antsy](https://www.v2ex.com/t/842896), aren't you right!? You can't get it right, can you, on both [free](https://www.autoptr.top/gdocr/GoldenDict-OCR-Deployment/) and unfree? And it's not that you are not technically proficient, but that not aiming at the right target and  not using your energy in the right way. 

https://user-images.githubusercontent.com/46510529/167539052-df39a9e7-55b7-4036-b5f5-ff0b9d06d3cd.mp4

Hahahahahaha, you'd be better to show off here than to go back to ploughing？Let's laugh out loud together, hahaha.

**Comment by nonwill** [comment]
@liuyonghao156 @ngn999 @xiaoyifang
> Please note that this version is non-free; use with your own discretion.

You techies are getting [antsy](https://www.v2ex.com/t/842896), aren't you right!? You can't get it right, can you, on both [free](https://www.autoptr.top/gdocr/GoldenDict-OCR-Deployment/) and unfree? And it's not that you are not technically proficient, but that not aiming at the right target and  not using your energy in the right way. 

And, excluding the porting of WebEngine, I'm a bit curious as to what has been done with so many commits in ten months?😁
![20220511151420](https://user-images.githubusercontent.com/46510529/167792337-1801e5f4-1cce-4d4f-9ad6-a390a6881f0b.png)
Hahahahahaha, you'd be better to show off here than to go back to ploughing？Let's laugh out loud together, hahaha.

https://user-images.githubusercontent.com/46510529/167539052-df39a9e7-55b7-4036-b5f5-ff0b9d06d3cd.mp4

**Comment by nonwill** [comment]
@liuyonghao156 @ngn999 @xiaoyifang
> Please note that this version is non-free; use with your own discretion.

You techies are getting [**antsy**](https://www.v2ex.com/t/842896), aren't you right!? You can't get it right, can you, on both [_free_](https://www.autoptr.top/gdocr/GoldenDict-OCR-Deployment/) and unfree? And it's not that you are not technically proficient, but that not aiming at the right target and  not using your energy in the right way. 

And, excluding the porting of WebEngine, I'm a bit curious as to _what has been done with so many commits i**n only ten months**_?😁
![20220511151420](https://user-images.githubusercontent.com/46510529/167792337-1801e5f4-1cce-4d4f-9ad6-a390a6881f0b.png)
Hahahahahaha, you'd be better to show off here than to go back to ploughing？Let's laugh out loud together, hahaha.

https://user-images.githubusercontent.com/46510529/167539052-df39a9e7-55b7-4036-b5f5-ff0b9d06d3cd.mp4

**Comment by nonwill** [comment]
A phase release for the latest macOS has been released and all are welcome：
[GoldenDict++OCR-3E0DD-macOS-(10.10~12.4)_Qt-5.15.4-universal-20220522](https://www.autoptr.top/gdocr/GoldenDict-OCR-Deployment/)  
![](https://www.autoptr.top/media/gdusage/forcedSearchSuggestions.gif)  
![](https://www.autoptr.top/media/gdusage/ignore_punctuations.gif)

**Comment by nonwill** [comment]
A phase release for the latest macOS has been released and all are welcome：
[GoldenDict++OCR-3E0DD-macOS-(10.10~12.4)_Qt-5.15.4-universal-20220522](https://www.autoptr.top/gdocr/GoldenDict-OCR-Deployment/)  
![](https://www.autoptr.top/media/gdusage/forcedSearchSuggestions.gif)  
![](https://www.autoptr.top/media/gdusage/ignore_punctuations.gif)

**Comment by nonwill** [comment]
[New releases](https://nonwill.github.io/gdocr/GoldenDict-OCR-Deployment/) for macOS/Linux/Windows [are now available](https://nonwill.github.io/gdocr/GoldenDict-OCR-Deployment/).
