### ISSUE TITLE
No entries with Chinese characters are displayed on XDXF dictionary

### ISSUE THREAD

**Issue by k-sl** [goldendict/goldendict#800]
I have recently written a [converter](https://github.com/k-sl/CedictXML) for the [CC-CEDICT](https://www.mdbg.net/chindict/chindict.php?page=cc-cedict) dictionary to XDXF format, unfortunately GoldenDict doesn't show any entry that actually has Chinese characters in it. The rare entries that have no Chinese characters show properly (including transcriptions, abbreviations, etc.). If an entry contains both Latin characters and Chinese characters it is also not displayed.

The Dictionary information shows the correct number of entries.

You can find a test file [here](https://github.com/k-sl/CedictXML/tree/master/CC-CEDICT.xdxf), which is exactly the file I am trying to use in GoldenDict.

Examples of entries that are displayed:
* A
* Q
* T
* 3C
* 3P
* OS

Examples of entries that are not:
* AA制
* DNA鑒定
* T恤
* 阿Q正傳

(And any common Chinese word consisting of Chinese characters:)
* 定时
* 共党
* 豆奶
* 每月
* 目无光泽

I am using GoldenDict ver. 1.5.0-RC2 in Manjaro Linux. I have also tried it on a Windows machine with the same results.

On [Alpus](http://ng-comp.com/alpus/index.html), the only other active DS that I know that supports XDXF  all entries are shown normally.

**Comment by Abs62** [comment]
I think this issue was fixed [here](https://github.com/goldendict/goldendict/commit/499a6835370f728d37d0a2c9793ba10634036d1f). You can build new version from sources or use last [EA build](https://github.com/goldendict/goldendict/wiki/Early-Access-Builds-for-Windows) under Windows. EA builds for Linux are not supported more than 3 years.

**Comment by k-sl** [comment]
I tried on both Linux and WIndows, on Linux from AUR (indicated as version.5.0RC2-5, released 2016-11-29) and on Windows exactly from the page you mentioned (1.5.0-RC2-36-gc689487, released 2016-10-27); I'm convinced this is the newest EA build. I noticed the bugfix you mentioned, I assumed It's either not related or not fixed for Chinese since it's still happening on the newest EA build.

**Comment by Abs62** [comment]
![gd-cc](https://cloud.githubusercontent.com/assets/837578/21777893/128b411e-d6b2-11e6-9b05-c4d78b98b8c2.png)

**Comment by k-sl** [comment]
I'm very glad to see it's working for you but the question remains, why can't I see any entry with Chinese characters? I'll retry tomorrow when I have access to a windows computer.

**Comment by k-sl** [comment]
![qq 20170110105453](https://cloud.githubusercontent.com/assets/24987537/21792420/a3c70dbc-d724-11e6-8c3b-89e9c1aecdc4.png)

![default](https://cloud.githubusercontent.com/assets/24987537/21792498/2f702394-d725-11e6-8b90-b509e287c632.png)

On a new intall on Windows 10.

**Comment by Abs62** [comment]
Have you tried Qt5-based version?

**Comment by k-sl** [comment]
![default](https://cloud.githubusercontent.com/assets/24987537/21795728/0e509c6a-d73f-11e6-9bef-9daa542bb766.png)

I hadn't. I have now and it is working. I suppose the problem you mentioned was fixed for the Qt5-compiled version but not for the Qt4-compiled one. I will be using the Qt5-based version from now one, the Qt4-based GoldenDict also needs to display non-latin characters.

[Quick off-topic: Ctrl-C stops working for copying when GoldenDict is open on Windows. Is it a well-known bug? Should I create a new issue?]

**Comment by Abs62** [comment]
Qt4 XML stream parser haven't such problem unlike Qt5. Check presence of qcncodecs4.dll file in "codecs" folder in your Qt4-based installation.

Concerning Ctrl-C: to use GD global hotkeys without such issues under Win8 and later you should run GD with admin rights.

**Comment by k-sl** [comment]
![default](https://cloud.githubusercontent.com/assets/24987537/21797674/746a3b30-d74b-11e6-926b-e49915334152.png)

There is indeed the file you mentioned.

Possibly interesting information: I noticed that after adding and indexing the dictionary on the Qt5 version all entries are displayed correctly on the Qt4 version, even after removing the dictionary, readding and re-indexing, it still works correctly. After removing all setting (through the uninstaller) it goes back the the original behaviour, not showing entries with Chinese characters.

[Not wanting to make this about the hotkeys: I don't use windows often, and I don't actually want to use the GD global hotkeys feature at all, but it is on by default and I have no way to know that is what's breaking the Ctr-C to copy feature. If this feature is well known to break basic functionality on modern versions of Windows, shouldn't it be off by default? And shouldn't users be warned when they turn it on?

**Comment by k-sl** [comment]
One additional problem which may or may not be related: This dictionary contains the entry "%". Even on the qt5-compiled version, which displays all other entries both on Windows and Linux this entry is not displayed, only showing "No translation for %25 was found in group All.", even though GoldenDict shows it on the lookup list.

![screenshot_20170114_185626](https://cloud.githubusercontent.com/assets/24987537/21954436/4d36f83a-da8b-11e6-9c16-2ed912b46e67.png)

**Comment by Abs62** [comment]
Different defaults inside Qt5 against Qt4. Fixed.  
New EXE for Windows: [goldendict-1.5.0-RC2-50-g2fe314a(EXE only).7z](http://www.mediafire.com/file/1kl8vtrkw380lee/goldendict-1.5.0-RC2-50-g2fe314a%28EXE+only%29.7z)

**Comment by k-sl** [comment]
![default](https://cloud.githubusercontent.com/assets/24987537/21969760/6412191c-dbdb-11e6-96c1-b28338aba6c2.png)

Thank you. I have confirmed this fixes the "%" problem on both Qt versions.
